### ISSUE TITLE
Android resource linking failed!

### ISSUE THREAD

**Issue by minaee** [lopspower/CircularImageView#100]
It works fine in android studio preview , but when lunch it in my phone, a build error says: `Android resource linking failed`! <br>
Is this error even related to this library? how can I fix this error?

**Comment by lopspower** [comment]
Sorry for the delay. I just updated the library, you can see [the release note here](https://github.com/lopspower/CircularImageView/releases/tag/4.0.0).

```groovy
implementation 'com.mikhaellopez:circularimageview:4.0.0'
```

If you still can try with the new version? I will close the ticket that can be reopened if the problem persists. Thank you, Mikhael.
