### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by furkanaskin** [lopspower/CircularImageView#101]
I have a Recyclerview and i'm binding svg images to CircularImageview. When the app is running profiler was showed 200-250 MB Memory usage. First of all, i thought "SVG is using too much memory." but you know SVGs lightweight and resizable. 

Finally, i just changed my CircularImageView with ImageView and problem fixed. Now, Android Profiler is showing 60 MB memory usage in runtime.

Check SVG support for CircularImageView.

**Comment by lopspower** [comment]
Duplicate of #98

**Comment by sagarnayak** [comment]
facing same problem in the recycler view.
