### ISSUE TITLE
not working (makes app to crach - test on genymotion android 9 and 6)

### ISSUE THREAD

**Issue by pcloudzaman** [lopspower/CircularImageView#102]
i've created a brand new app and this is my xml:
adding civ library causes app to crash
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">
tesed on genymotion android 9 and android 6
    <com.mikhaellopez.circularimageview.CircularImageView
        android:layout_width="250dp"
        android:layout_height="250dp"
        android:src="@drawable/flash"
        app:civ_border_color="#3f51b5"
        app:civ_border_width="4dp"
        app:civ_shadow="true"
        app:civ_shadow_radius="10"
        app:civ_shadow_color="#3f51b5"/>

</LinearLayout>

**Comment by lopspower** [comment]
Can you send me more information about your crash ? What crash do you have ? Can you send the flash drawable ?

**Comment by pcloudzaman** [comment]
here are the flash.png and flash.jpg
and for reproducing the problem, I just create a new android studio project (latest version of android studio, and latest version of sdk, min sdk 18, targetsdk29) and use genymotion android 9 and add dependency in gradle and the above code in main activity xml. 
https://www.dropbox.com/s/sfny2oacp62hqis/flash.png?dl=1
https://www.dropbox.com/s/m6z13mk3l5f8rd3/flash.jpg?dl=1

**Comment by lopspower** [comment]
Thank you for you feedback @pcloudzaman 
I try to find your problem with your last repository: [https://github.com/pcloudzaman/MyApplication5](https://github.com/pcloudzaman/MyApplication5)

The problem is that the latest version of CircularImageView is in **Kotlin** and your project is in **Java**.
To solve the problem, you must add the kotlin-stdlib dependency in your project:

```
implementation "org.jetbrains.kotlin:kotlin-stdlib:1.3.40"
```

<img src="https://i.ibb.co/HH3MnX0/device-2019-06-27-101307.png" height="400" width="225" />

**Comment by pcloudzaman** [comment]
thank you very very much for your help
and thank you again for this amazing library.

**Comment by lopspower** [comment]
Thank you for your feedback @pcloudzaman
I will try to correct the problem so that I don't need to add this dependency in the next version.

**Comment by pcloudzaman** [comment]
thanks

**Comment by lopspower** [comment]
I publish a new version of this library with this fix:
https://github.com/lopspower/CircularImageView/releases/tag/4.0.1

```groovy
implementation 'com.mikhaellopez:circularimageview:4.0.1'
```
