### ISSUE TITLE
Unable to clear ColorFilter

### ISSUE THREAD

**Issue by imyrfield** [lopspower/CircularImageView#106]
It seems the library doesn't allow you to "reset" a `ColorFilter` once applied. The platform `ImageView` has a `.clearColorFilter()` but we're unable to use that with this library because the overridden method doesn't accept `null` values (which is a bit odd because the internal `civColorFilter` variable is nullable).

Would it be possible to update:
` override fun setColorFilter(colorFilter: ColorFilter) {
        civColorFilter = colorFilter
    }`

to: 
` override fun setColorFilter(colorFilter: ColorFilter?) {
        civColorFilter = colorFilter
    }`

**Comment by lopspower** [comment]
Thank you for your feedback. It's now fixed on the last version:

```groovy
implementation 'com.mikhaellopez:circularimageview:4.0.2'
```

**Comment by imyrfield** [comment]
Thanks you for addressing this so quickly :)
