### ISSUE TITLE
Not showing using 3.1.0 version

### ISSUE THREAD

**Issue by rupert2133** [lopspower/CircularImageView#108]
Image is showing in xml but after running the app, the circular image is not showing..

> <com.mikhaellopez.circularimageview.CircularImageView
                        android:id="@+id/img_profile"
                        android:layout_width="100dp"
                        android:layout_height="100dp"
                        android:layout_centerHorizontal="true"
                        android:layout_alignParentBottom="true"
                        android:layout_marginTop="30dp"
                        android:layout_marginBottom="20dp"
                        android:tint="@color/grey_20"
                        app:civ_border="true"
                        app:civ_border_width="10dp"
                        app:civ_border_color="@color/white"
                        app:srcCompat="@drawable/ic_person_black_24dp" />

**Comment by lopspower** [comment]
Can you send your image `ic_person_black` and the value of your color `grey_20` please ?

**Comment by rupert2133** [comment]
Hi sir, here's the `ic_person_black` xml file that I'm using https://drive.google.com/drive/folders/1-HGPTT_ONJSVNCck2ZT-8ZC0WHl8GpGY?usp=sharing
and here's the color of `grey_20` -> 
` <color name="grey_20">#cccccc</color>`

**Comment by lopspower** [comment]
Everything works fine with the latest version of CircularImageView. Please make the update:

```groovy
implementation 'com.mikhaellopez:circularimageview:4.0.2'
```

Be careful with `app:civ_border_color="@color/white"`: If you use white with a vector drawable (so the background of the image is transparent) the background circle is also white so the border is not visible.

<img src="https://i.ibb.co/G579RYv/device-2019-08-22-102212.png" width="200" height="189">
