### ISSUE TITLE
Caused by java.lang.OutOfMemoryErrorFailed to allocate a 7091580 byte allocation with 6682456 free bytes and 6MB until OOM Raw Text

### ISSUE THREAD

**Issue by AnilTiVo** [lopspower/CircularImageView#110]
Caused by java.lang.OutOfMemoryErrorFailed to allocate a 7091580 byte allocation with 6682456 free bytes and 6MB until OOM Raw Text
--
  | dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
  | android.graphics.BitmapFactory.nativeDecodeAsset (BitmapFactory.java)
  | android.graphics.BitmapFactory.decodeStream + 620 (BitmapFactory.java:620)
  | android.graphics.BitmapFactory.decodeResourceStream + 455 (BitmapFactory.java:455)
  | android.graphics.drawable.Drawable.createFromResourceStream + 1152 (Drawable.java:1152)
  | android.content.res.ResourcesImpl.loadDrawableForCookie + 720 (ResourcesImpl.java:720)
  | android.content.res.ResourcesImpl.loadDrawable + 571 (ResourcesImpl.java:571)
  | android.content.res.Resources.loadDrawable + 858 (Resources.java:858)
  | android.content.res.TypedArray.getDrawable + 928 (TypedArray.java:928)
  | android.widget.ImageView.<init> + 162 (ImageView.java:162)
  | android.widget.ImageView.<init> + 150 (ImageView.java:150)
  | android.support.v7.widget.AppCompatImageView.<init> + 72 (AppCompatImageView.java:72)
  | com.mikhaellopez.circularimageview.CircularImageView.<init> + 56 (CircularImageView.java:56)
  | com.mikhaellopez.circularimageview.CircularImageView.<init> + 52 (CircularImageView.java:52)
  | java.lang.reflect.Constructor.newInstance0 (Constructor.java)
  | java.lang.reflect.Constructor.newInstance + 430 (Constructor.java:430)
  | android.view.LayoutInflater.createView + 645 (LayoutInflater.java:645)
  | android.view.LayoutInflater.createViewFromTag + 787 (LayoutInflater.java:787)
  | android.view.LayoutInflater.createViewFromTag + 727 (LayoutInflater.java:727)
  | android.view.LayoutInflater.rInflate + 858 (LayoutInflater.java:858)
  | android.view.LayoutInflater.rInflateChildren + 821 (LayoutInflater.java:821)
  | android.view.LayoutInflater.inflate + 518 (LayoutInflater.java:518)
  | android.view.LayoutInflater.inflate + 426 (LayoutInflater.java:426)
  | com.tivo.blackph.view.nav.NavFragment.onCreateView + 147 (NavFragment.java:147)
  | android.support.v4.app.Fragment.performCreateView + 2439 (Fragment.java:2439)
  | android.support.v4.app.FragmentManagerImpl.moveToState + 1460 (FragmentManager.java:1460)
  | android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState + 1784 (FragmentManager.java:1784)
  | android.support.v4.app.FragmentManagerImpl.moveToState + 1852 (FragmentManager.java:1852)
  | android.support.v4.app.BackStackRecord.executeOps + 802 (BackStackRecord.java:802)
  | android.support.v4.app.FragmentManagerImpl.executeOps + 2625 (FragmentManager.java:2625)
  | android.support.v4.app.FragmentManagerImpl.executeOpsTogether + 2411 (FragmentManager.java:2411)
  | android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 2366 (FragmentManager.java:2366)
  | android.support.v4.app.FragmentManagerImpl.execPendingActions + 2273 (FragmentManager.java:2273)
  | android.support.v4.app.FragmentManagerImpl$1.run + 733 (FragmentManager.java:733)
  | android.os.Handler.handleCallback + 751 (Handler.java:751)
  | android.os.Handler.dispatchMessage + 95 (Handler.java:95)
  | android.os.Looper.loop + 154 (Looper.java:154)
  | android.app.ActivityThread.main + 6088 (ActivityThread.java:6088)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 886 (ZygoteInit.java:886)
  | com.android.internal.os.ZygoteInit.main + 776 (ZygoteInit.java:776)

I got this when I added this into my app:
>  | com.mikhaellopez.circularimageview.CircularImageView.<init> + 56 (CircularImageView.java:56)
>  | com.mikhaellopez.circularimageview.CircularImageView.<init> + 52 (CircularImageView.java:52)

Can you please help?

**Comment by lopspower** [comment]
[Issue 98](https://github.com/lopspower/CircularImageView/issues/98)

**Comment by AnilTiVo** [comment]
Issue is still there even after adding **android:hardwareAccelerated="false"** in application manifest.

**Comment by lopspower** [comment]
Juste resize your image

**Comment by AnilTiVo** [comment]
Hmm. That would work for static images.
What should be done incase Images are coming from server?

**Comment by lopspower** [comment]
The problem does not come from this library, the behavior is the same with a classic ImageView. The phone you use does not have enough RAM to display such a big picture. To correct the problem you must reduce the image before displaying it.
