### ISSUE TITLE
Copyright notice for CircularImageView

### ISSUE THREAD

**Issue by flobetz** [lopspower/CircularImageView#111]
Hey Lopez,
we are using your CircularImageView library within our Android App and we have to list your library within our FOSS components. Therefore we need a Copyright notice which is, unfortunately, not available in this repo.
Can you please provide this oneliner?
Greetings
Flo

**Comment by lopspower** [comment]
Hey Flo,
This library its already under [APACHE LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0).
So you can used it in your project.
Thanks, Mikhael.

**Comment by flobetz** [comment]
found it, thanks!
