### ISSUE TITLE
Shadow issue with Theme.MaterialComponents

### ISSUE THREAD

**Issue by fgnm** [lopspower/CircularImageView#114]
Hi, I've noticed a issue very similar to #31 but that appears only when the app uses as base theme `Theme.MaterialComponents` with Android 6.0 (Instead with Android 9 and 10 no issue).

A workaround is to disable shadow `app:civ_shadow="false"`, anyway I hope that you will fix this issue, thank you.

**Comment by lopspower** [comment]
I used the sample available in the repo. I changed the parent theme to `Theme.MaterialComponents.Light` after adding the dependency `com.google.android.material: material: 1.2.0-alpha02`.
I installed the application on an **Android 6 device** (api 23) and I have no problem even with the shadow (`app:civ_shadow="true"`).

Do you have more information on the problem that could help me to reproduce it too?

<img src="https://i.ibb.co/cwfYV9t/Screenshot-1575045904.png" width="300" height="533" />

**Comment by KyawSoeW1n** [comment]
@lopspower  Try on recyclerview and app:civ_shadow="true".
You will see that black background will appear.
