### ISSUE TITLE
The image does't load correctly the first time you run the app 

### ISSUE THREAD

**Issue by johnjeremih** [lopspower/CircularImageView#115]
I tried with several phones and it continues to happen, but when I go to another layout and then come back it goes back to normal. This issue started after you include the gradients.
<img width="283" alt="Screen Shot 2019-12-02 at 1 02 58 PM" src="https://user-images.githubusercontent.com/4177453/69983471-c35e2180-1504-11ea-94d0-3515d03157b6.png">

**Comment by lopspower** [comment]
Hello,
can you send me more information about this issue (code, image..). I can't reproduce it.

**Comment by johnjeremih** [comment]
I will attach some screenshots.
<img width="568" alt="Screen Shot 2019-12-04 at 9 01 48 PM" src="https://user-images.githubusercontent.com/4177453/70197371-a3338b80-16d9-11ea-992e-a59939c3f8cb.png">
<img width="678" alt="Screen Shot 2019-12-04 at 9 00 05 PM" src="https://user-images.githubusercontent.com/4177453/70197372-a3338b80-16d9-11ea-97fc-8d59e0647451.png">

**Comment by johnjeremih** [comment]
I found out the reason why is it looks like that. The problem only happens with Java. In Kotlin works fine

**Comment by lopspower** [comment]
Hello, I find the problem. I will deploy new version of the library today with the fix.

**Comment by lopspower** [comment]
This is fix on the last version:

```groovy
implementation 'com.mikhaellopez:circularimageview:4.1.1'
```
