### ISSUE TITLE
Hello need some help

### ISSUE THREAD

**Issue by UmairAhmed420** [lopspower/CircularImageView#118]
Although your library is good and nearly problem solving.... but still there is a bit issue ... it put default border of white which is annoyed and when i increase shadow radius it makes my image small and de-pixelate ... Kindly help me over it

**Comment by lopspower** [comment]
Add this property to remove the border:
`app:civ_border="false"`

Yes the view in your layout has a size. If you increase the radius of the shadow it will push the image towards the center of your view. You have to adapt your layout if you want the shadow to go over the other views.

**Comment by UmairAhmed420** [comment]
is there a way or can u provide some way to overcome it? because as my image push at center it gets blurry ... how about increase shadow by expanding it without being push image in center
