### ISSUE TITLE
Not working when on LinearLayout I assing weight

### ISSUE THREAD

**Issue by RafaRuiz** [lopspower/CircularImageView#12]
These are 3 normal ImageViews distributed with the same weight:

    <LinearLayout 
        android:id="@+id/l1" 
        android:background="@drawable/sfondoedittextmessaggi" 
        android:layout_width="fill_parent" 
        android:layout_height="wrap_content" 
        android:layout_alignParentLeft="true" 
        android:layout_alignParentTop="true">
        <ImageView 
            android:id="@+id/immagine1"
            android:layout_width="0.0dip" 
            android:layout_height="fill_parent" 
            android:layout_margin="@dimen/marginPiccolo"
            android:src="@drawable/nofoto" 
            android:layout_weight="1.0" />
        <ImageView 
            android:id="@+id/immagine2" 
            android:layout_width="0.0dip" 
            android:layout_height="fill_parent" 
            android:layout_margin="@dimen/marginPiccolo" 
            android:src="@drawable/nofoto" 
            android:adjustViewBounds="true" 
            android:layout_weight="1.0" />
        <ImageView 
            android:id="@+id/immagine3" 
            android:layout_width="0.0dip" 
            android:layout_height="fill_parent" 
            android:layout_margin="@dimen/marginPiccolo" 
            android:src="@drawable/nofoto" 
            android:adjustViewBounds="true" 
            android:layout_weight="1.0" />
    </LinearLayout>

![image](https://cloud.githubusercontent.com/assets/6842786/3247537/404858a4-f185-11e3-84c9-2a49413a330e.png)

and these changing to CircularImageView:

![image](https://cloud.githubusercontent.com/assets/6842786/3247556/6c9c90f0-f185-11e3-9640-8799c65543b2.png)

**Comment by lopspower** [comment]
This is fix, thank you :)
