### ISSUE TITLE
scaletype="centerinside" makes the edges of the image stretch

### ISSUE THREAD

**Issue by zubairzahoor** [lopspower/CircularImageView#120]
The sides of the image are stretched when using centerinside as scale type.

**Comment by lopspower** [comment]
The problem comes from vector images. This is now fixed in the new version:
```groovy
implementation 'com.mikhaellopez:circularimageview:4.2.0'
```

**Comment by NStreet8579** [comment]
I'm Facing this issue still. @lopspower
