### ISSUE TITLE
Image src doesn't change from java

### ISSUE THREAD

**Issue by mahdiazarm** [lopspower/CircularImageView#122]
Hi!
`setImageResource`, `setImageDrawable`, `ContextCompat.getDrawable` and any other same methods doesn't change circularimageview src from java.
I replaced circularimageview with normal ImageView and everything works fine.
Is it an issue or i missed something?

**Comment by kushagrasaxena2019** [comment]
you have to put your image view in CardView because only CardView has a feature of accessing the corner radius attribute.

**Comment by lopspower** [comment]
Hi,
It works well on my side. You can test on the sample :
```kotlin
circularImageView.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.logo))
```
or with java
```java
circularImageView.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.logo));
```
