### ISSUE TITLE
Migrate to other repository because JCenter is closing

### ISSUE THREAD

**Issue by herisulistiyanto** [lopspower/CircularImageView#132]
Hi, is it possible to migrate this library into maven central? since Jcenter is closing.
Checked into mvn repos and latest lib isn't mirror into central as well.

[https://mvnrepository.com/artifact/com.mikhaellopez/circularimageview](https://mvnrepository.com/artifact/com.mikhaellopez/circularimageview)

**Comment by nicemak** [comment]
@lopspower any update?

**Comment by lopspower** [comment]
Sorry for the delay 🙏
The version 4.3.0 is now available on MavenCentral :
```groovy
implementation 'com.mikhaellopez:circularimageview:4.3.0'
```
