### ISSUE TITLE
android.view.InflateException:  Error inflating

### ISSUE THREAD

**Issue by NexoVentas-Android** [lopspower/CircularImageView#137]
android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.mikhaellopez.circularimageview.CircularImageView
    Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.mikhaellopez.circularimageview.CircularImageView

while on line no 17 that`s the line of code 
 app:civ_border_width="0.5dp"

 <com.mikhaellopez.circularimageview.CircularImageView
        android:id="@+id/img"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:scaleType="centerCrop"
        android:src="@drawable/oil"
        app:civ_border_color="@color/light_gray"
        app:civ_border_width="0.5dp" />

color: = 
    <color name="light_gray">@android:color/darker_gray</color>
    <color name="darker_gray">#aaa</color>

**Comment by lopspower** [comment]
No issue with the same code on the latest version on my side.
