### ISSUE TITLE
Out Of Memory from BitmapShader

### ISSUE THREAD

**Issue by hongzhou85** [lopspower/CircularImageView#14]
BitmapShader shader = new BitmapShader(Bitmap.createScaledBitmap(image, canvasSize, canvasSize, false), Shader.TileMode.CLAMP, Shader.TileMode.CLAMP);

07-03 16:34:02.687: E/AndroidRuntime(4886): FATAL EXCEPTION: main
07-03 16:34:02.687: E/AndroidRuntime(4886): java.lang.OutOfMemoryError
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.graphics.Bitmap.nativeCreate(Native Method)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:686)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at com.mikhaellopez.circularimageview.CircularImageView.onDraw(CircularImageView.java:83)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.View.draw(View.java:15303)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.View.getDisplayList(View.java:14197)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.View.getDisplayList(View.java:14239)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.View.draw(View.java:15017)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.View.draw(View.java:15306)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.View.getDisplayList(View.java:14197)
07-03 16:34:02.687: E/AndroidRuntime(4886): 	at android.view.View.getDisplayList(View.java:14239)

Anyone face this error? How do we resolve bitmap shader out of memory. It occurs in some devices, not all.

**Comment by aakashbapna** [comment]
+1 got this too.

**Comment by lopspower** [comment]
Lot of fix to this library. I think they fix this.

**Comment by Leonid-Kiev** [comment]
+1
