### ISSUE TITLE
Dynamic image change not working

### ISSUE THREAD

**Issue by bizkit1** [lopspower/CircularImageView#16]
I managed to implement this, it works fine with static images. In my case i have a radio app, and the artist image refreshes everytime the song changes.  If i apply the circularimageview in my xml layout file, when the image changes my app crashes.
Any ideea why?

**Comment by katalin2003** [comment]
Hello @bizkit1 have you found a solution to this?
I tried using CircularImageView with NetworkImageView to no avail.

Thanks
