### ISSUE TITLE
Image view not working for 10'' tablet

### ISSUE THREAD

**Issue by dharajogi** [lopspower/CircularImageView#19]
![device-2014-08-06-192722](https://cloud.githubusercontent.com/assets/8089945/3827923/a67b88bc-1d72-11e4-930d-365f68d1b7be.png)
![device-2014-08-06-192731](https://cloud.githubusercontent.com/assets/8089945/3827925/ab8defac-1d72-11e4-9b36-15f4d5238006.png)

the first image is from 10'' tablet and second is from note 2 mobile 
i need to know the reason why it is not working for tablet.
Can you please help me out.

**Comment by lopspower** [comment]
I update this library, I think the modification fix this :)
