### ISSUE TITLE
Gravity problem in linearLayout with given weight parameter

### ISSUE THREAD

**Issue by enessen** [lopspower/CircularImageView#20]
if you add circularImageView in a linearLayout and give weight instead of fixed width and heigth then CircularImageView is not accepting gravity parameter of parent layout.

in your onMeasuer method you should assume that circularImageView has always square canvas so you should add "int min = Math.min(width, height);" and set this min as measured dimension in your code like below;

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int width = measureWidth(widthMeasureSpec);
        int height = measureHeight(heightMeasureSpec);
        **int min = Math.min(width, height);**
        setMeasuredDimension(min, min);
    }

**Comment by lopspower** [comment]
Now the library work well with weight param. Thank you for your contribution.
