### ISSUE TITLE
Don't create a new shader in every call to onDraw().

### ISSUE THREAD

**Issue by simonedstromsi** [lopspower/CircularImageView#23]
Creating a new shader and bitmap in every call to onDraw (up to 60times / second) is very bad for performance. 

Try creating the shader in onSizeChanged() to make sure your bitmap has the right size.

**Comment by samskiter** [comment]
:+1: although onDraw would only be called up to 60times /seconds if you were animating the size of the view or something

**Comment by simonedstromsi** [comment]
Or if it's in a list that scrolls :)

**Comment by samskiter** [comment]
@simonedstromsi not as far as i'm aware - it will simply be snapshotted and moved, ondraw won't be called

**Comment by simonedstromsi** [comment]
Ok :) I wasn't aware of that.

**Comment by samskiter** [comment]
@lopspower this is still an issue isn't it. AFAICT this is still the case... can submit a PR if you like, normally it just requires overriding onSizeChanged

**Comment by lopspower** [comment]
Yes if you can, I want a PR :)

**Comment by samskiter** [comment]
Done :)
