### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by www40** [lopspower/CircularImageView#24]
I would love to use this lib with gradle, so can you please upload it to mavencentral?

**Comment by jitpack-io** [comment]
Hi!
It's possible to install it using:
https://jitpack.io/#lopspower/CircularImageView/35b3238030

**Comment by lopspower** [comment]
I work now to fix this issue with this tutorial https://github.com/danielemaddaluno/gradle-jcenter-publish :)

**Comment by lopspower** [comment]
I definitely don't seem to do that !! I need help ..
http://stackoverflow.com/questions/33104152/publish-github-android-library-to-maven-central

**Comment by lopspower** [comment]
You can now add this library with gradle like : 
```groovy
compile 'com.mikhaellopez:circularimageview:2.0.1'
```
