### ISSUE TITLE
Allow to configure shadow params

### ISSUE THREAD

**Issue by anticafe** [lopspower/CircularImageView#30]
I see the method `addShadow` in your code
>paintBorder.setShadowLayer(4.0f, 0.0f, 2.0f, Color.BLACK);

Could you please allow us to set shadow param (radius, dx, dy by dip, color) programmatically, or in xml?

**Comment by lopspower** [comment]
I update this library for you with two new params: 

* `app:shadow_color`    (color)     -> default BLACK
* `app:shadow_radius`  (float)     -> default 8.0f

Or programmatically: 

```java
CircularImageView circularImageView = (CircularImageView)findViewById(R.id.yourCircularImageView);
// Add Shadow with default param
circularImageView.addShadow();
// or with custom param
circularImageView.setShadowRadius(15);
circularImageView.setShadowColor(Color.RED);
```

Note: ```dx = 0``` and ```dy = shadowRadius / 2``` to keep a good ratio.

You can used this update with gradle:

```groovy
compile 'com.mikhaellopez:circularimageview:2.0.2'
```

**Comment by anticafe** [comment]
Thank you for your hard work :)
