### ISSUE TITLE
Image unwanted black background

### ISSUE THREAD

**Issue by DenisMondon** [lopspower/CircularImageView#31]
Hi!

I have a black background when using your walter image. But when using a transparent image (ic_launcher), it works perfectly... I can't find the solution. Can you help me?

Here is the screenshot:
![device-2015-10-29-125401](https://cloud.githubusercontent.com/assets/1906100/10817773/7db461b6-7e3c-11e5-897f-876a17773104.png)
And here is the xml code:
```xml
            <com.mikhaellopez.circularimageview.CircularImageView
                android:layout_width="96dp"
                android:layout_height="96dp"
                android:scaleType="centerCrop"
                android:src="@drawable/walter"
                app:border="true"
                app:border_color="@android:color/white"
                app:border_width="3dp"
                app:shadow="true"
                app:shadow_color="#000000"
                app:shadow_radius="6"/>

            <com.mikhaellopez.circularimageview.CircularImageView
                android:layout_width="96dp"
                android:layout_height="96dp"
                android:scaleType="centerCrop"
                android:src="@drawable/ic_launcher"
                app:border="true"
                app:border_color="@android:color/white"
                app:border_width="3dp"
                app:shadow="true"
                app:shadow_color="#000000"
                app:shadow_radius="6"/>
```

**Comment by lopspower** [comment]
The problem came from the property `android:scaleType="centerCrop"`.
Indeed, you don't need to use it, since this property is automatically manage in the library.
But thank you for your return, I'll still try to correct this point if someone uses it again.

**Comment by DenisMondon** [comment]
Oh thank you! I didn't think about that!
Have a good day! Thanks a lot.
Denis

**Comment by mohammadrafigh** [comment]
I have the same issue exactly with your sample code in readme.md and without scaleType

**Comment by lopspower** [comment]
Please download the sample project "circularimageview-example" and try to see the difference with your implementation.

**Comment by m1ga** [comment]
Same here. Gif is working fine, a jpg has a black background

**Comment by m1ga** [comment]
Tried https://github.com/vinc3m1/RoundedImageView and it worked with the same JPG file and no black background. But it doesn't feature the nice dropshadow, so your module would be a better alternative :)

**Comment by lopspower** [comment]
I actually identified the problem.
I posted a question on [stackoverflow](http://stackoverflow.com/questions/35630180/black-background-or-square-view-in-custom-imageview) if you want to try to contribute.

**Comment by lopspower** [comment]
@m1ga Do you know if with RoundedImageView your view is centered when you integrate your view in the view parent with `android:gravity="center"` this way:

```xml
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:orientation="vertical">

        <CustomView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

</LinearLayout>
```

**Comment by m1ga** [comment]
yes it's 
~~~
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:background="#ffffff"
    android:orientation="vertical">
~~~

**Comment by lopspower** [comment]
I had new release to fix that temporarily but you must specify the size of the view if you added to a parent view using a gravity:

```groovy
compile 'com.mikhaellopez:circularimageview:3.0.2'
```

**Comment by priegler** [comment]
I still have the same issue as described (I am on v3.0.2). Any updates on that one? In my case I defined the size of the view as you suggested @lopspower

**Comment by priegler** [comment]
I found out that the black background disappears when I use  `app:civ_shadow="false"`. 
So what I do now as a workaround is to activate the shadow in code. 
Then everything works. 
Maybe this helps someone too.

**Comment by priegler** [comment]
I played arround for some time now and found out that the black background disappears when I use app:civ_shadow="false". 
So what I do now as a workaround is to activate the shadow in code `circularImageView.addShadow();` 
Then everything works unless I also add `setShadowColor` (which again causes the black background).

Maybe this helps to fix the issue?
