### ISSUE TITLE
Image is the wrong size

### ISSUE THREAD

**Issue by Philio** [lopspower/CircularImageView#32]
The images are always slightly too small, e.g. here is a 40dp x 40dp image (Amazon logo) with a 40dp x 40dp blue circle behind it:

![device-2015-11-11-233819](https://cloud.githubusercontent.com/assets/237850/11106389/bb76adc4-88cd-11e5-8ffd-7ba5bf1cfedc.png)

        <ImageView
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:layout_marginLeft="16dp"
            android:layout_marginStart="16dp"
            android:background="@drawable/cicular_mask" />

        <com.mikhaellopez.circularimageview.CircularImageView
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:layout_marginLeft="16dp"
            android:layout_marginStart="16dp"
            app:border="false"
            app:imageUrl="@{entry.imageUrl}"
            app:shadow="false" />

**Comment by Philio** [comment]
The issue is that the default value of `shadowRadius` is 8, so even when the shadow is set to false the size of the image is calculated using that value. Setting the radius to 0 in the layout is a work around.

**Comment by DenisMondon** [comment]
Nice workaround!
Adding this solves the problem:
```xml
app:shadow="true"
app:shadow_radius="0"
```

**Comment by lopspower** [comment]
Thank you for this return.
I will fix that as soon as I come to you. It's not much but I need a little personal time for that.
This is why it takes a little time.

**Comment by lopspower** [comment]
This issue is Fixed with new release : 
```groovy
compile 'com.mikhaellopez:circularimageview:2.1.0'
```

**Comment by Philio** [comment]
Thanks for fixing! Confirmed working on latest build.
