### ISSUE TITLE
Glide not updating to the final image

### ISSUE THREAD

**Issue by jmspt** [lopspower/CircularImageView#35]
Hi, Jorge here!

When I use Glide to load an image from Internet and setted a placeholder, the CircularImagewView not updating to the final image, always show the placeholder.

Can you resolve the problem?

Thank you

**Comment by DenisMondon** [comment]
I fixed this by adding .asBitmap() to the glide code :
```java
Glide.with(getContext()).load(pictureUrl)
                .asBitmap()
                .placeholder(R.drawable.ic_test).into(mPicture);
```
Denis

**Comment by hzsweers** [comment]
What if the image is actually animated though?
