### ISSUE TITLE
Possible setBorder(true|false) ?

### ISSUE THREAD

**Issue by DenisMondon** [lopspower/CircularImageView#36]
Hi, I would like to remove or add at runtime the border.
For now, I'm using setBorderWidth(0) to remove it...

Is it possible to add the .setBorder(boolean) method?

Thanks
Denis

**Comment by lopspower** [comment]
By default there is no Shadow. So you don't need this method. 

```java
// Init Shadow
if (attributes.getBoolean(R.styleable.CircularImageView_shadow, false)) {
    drawShadow(attributes.getFloat(R.styleable.CircularImageView_shadow_radius, shadowRadius), attributes.getColor(R.styleable.CircularImageView_shadow_color, shadowColor));
}
```

However, there is indeed a bug that will be fixed soon which will no longer be used by default value of 8 shadow radius which distorts the image.

**Comment by DenisMondon** [comment]
I talked about the border :) not the shadow :/

**Comment by lopspower** [comment]
Hoo sorry !!
For this you just need to add the following property in your XML:
`app:border="false"`

**Comment by DenisMondon** [comment]
Yes thanks but at runtime? xD

**Comment by lopspower** [comment]
Why you need to remove border at runtime ?
If you need to change the size of the border, so in that case, you need to use just `setBorderWidth(0)`
