### ISSUE TITLE
Could not change the size of the <com.mikhaellopez.circularimageview.CircularImageView

### ISSUE THREAD

**Issue by Shajeel-Afzal** [lopspower/CircularImageView#4]
Hi i am changing the size as follows: <com.mikhaellopez.circularimageview.CircularImageView
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:layout_gravity="center_vertical|center_horizontal"
        android:layout_margin="20dp"
        android:scaleType="fitXY"
        android:src="@drawable/my_pic"
        app:border="true"
        app:border_width="10" />

but the it is not correctly changed. 
I am getting this view after changing the width and height as above:
![capture](https://cloud.githubusercontent.com/assets/3718283/2659888/68acd876-c019-11e3-81a9-f43d9807d2ef.JPG)

Can you explain why it is not working?

**Comment by mayurpadhye** [comment]
@Shajeel-Afzal  did you get the issue

**Comment by lopspower** [comment]
Hello @mayurpadhye this is an old issue. Try with new version of this library and maybe create new issue if it's doesn't work.
