### ISSUE TITLE
Request: allow to use elevation when on Android 5.0 and above, to replace the shadow

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [lopspower/CircularImageView#41]
On most cases, I assume people will want the built in shadow, which is cast via "elevation".

It's more efficient and looks nice, so please add this feature. 
Only thing it lacks is a shadow color

**Comment by lopspower** [comment]
Thank you for all your questions.
You can participate in improving the library by providing a pull to request !!

**Comment by AndroidDeveloperLB** [comment]
Sadly I don't know how to do it (both the elevation and the pull request).
If you wish, you can check out my repos too :)

**Comment by AndroidDeveloperLB** [comment]
Do you know how to make the image centered without cropping though?

**Comment by AndroidDeveloperLB** [comment]
@lopspower I actually do have a suggestion of something to look at.
I don't know how the repo implements the cropping and rounding of the input bitmap, but there is a way to do so without creating a new bitmap, thus making it more memory efficient and faster:

http://stackoverflow.com/a/18207425/878126

**Comment by AndroidDeveloperLB** [comment]
I think it's possible using this function:

 public static void setOvalElevationToImageView(final ImageView imageView) {
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP)
            imageView.setOutlineProvider(new ViewOutlineProvider() {
                @TargetApi(VERSION_CODES.LOLLIPOP)
                @Override
                public void getOutline(View view, Outline outline) {
                    final int size = imageView.getWidth();
                    outline.setOval(0, 0, size, size);
                }
            });
    }

Can you please try it out?

**Comment by lopspower** [comment]
It's now available on the last version of library:

```groovy
implementation 'com.mikhaellopez:circularimageview:4.0.0'
```
