### ISSUE TITLE
Question: How to have equal shadow width around image

### ISSUE THREAD

**Issue by ggun69** [lopspower/CircularImageView#43]
Thank you for your job!

Do you know how to set identical shadow width around the circle ? I have tried:
app:shadow-radius="4"
or
paint.setShadowLayer(4.0f, 4.0f, 4.0f, Color.BLACK)
but shadow is bigger at circle bottom than at circle top

**Comment by krissrex** [comment]
Parameters dx and dy should be 0 to center the shadow:

```java
// CircularImageView.java line 164
paintBorder.setShadowLayer(shadowRadius, 0.f, 0.f, shadowColor); 
```

Look at [setShadowLayer(float radius, float dx, float dy, int shadowColor)](http://developer.android.com/reference/android/graphics/Paint.html#setShadowLayer\(float, float, float, int\)).
