### ISSUE TITLE
Issues working with Glide - Black background appears

### ISSUE THREAD

**Issue by tomtaila** [lopspower/CircularImageView#45]
I'm using Glide (image loading/manipulating/caching library https://github.com/bumptech/glide) which is very popular to load images into the circular views. Suppose I do this for the first time in the app lifecycle it works fine but when i close the activity I do this on and return to it suddenly the circle image had a black background around it. This produces the effect of a surrounding black box. Please fix this.

**Comment by tomtaila** [comment]
I just noticed something which seems to imply it's related to the center crop issues you're having.
The following are code snippets of image loading where one snippet results in the error mentioned above and one doesnt:

WITH ERROR:
Glide.with(this).load(R.drawable.profile_pic).crossFade().centerCrop().into(imageView);

WithOUT ERROR:
Glide.with(this).load(R.drawable.profile_pic).crossFade().into(imageView);

Notice that the first snippet (WITH error) involves using the "centerCrop()" method provided by Glide and the second doesn't.

**Comment by lopspower** [comment]
The property `centerCrop` base is used because it is a circular image.
You actually do not need this property.
