### ISSUE TITLE
Image With Transparency

### ISSUE THREAD

**Issue by Jayvd** [lopspower/CircularImageView#46]
Hi, thank you for providing such a usefull library.

However, there is one problem.

When we use a PNG image with transparency, the border_color fills all the transparent area.

Is there any possibility where you can add an Image background Color feature for this kind of situation? so the border stays the same.

Thank you for creating this library again

**Comment by lopspower** [comment]
Hi,
You only need to change the color of the border for that:
`app:border_color="@color/your_color"`
or
`circularImageView.setBorderColor(getResources().getColor(R.color.your_color));`
