### ISSUE TITLE
padding render image missed pixel

### ISSUE THREAD

**Issue by sinhpn92** [lopspower/CircularImageView#47]
I have an issue with my app.
When I set a image for my imageview with your lib, the Circle Image View have missed pixel around image. 
<img width="417" alt="screen shot 2016-01-21 at 10 11 26 am" src="https://cloud.githubusercontent.com/assets/9253441/12470537/b2e01c36-c027-11e5-8083-1338f46bfccd.png">

You can see the photos to better understand my issue.
How can i fix it? Thanks.

**Comment by lopspower** [comment]
I don't know how to fix it.
This is the result of the native method: `canvas.drawCircle()`
