### ISSUE TITLE
Could not find method android.widget.ImageView.<init>

### ISSUE THREAD

**Issue by DenisZhadan** [lopspower/CircularImageView#48]
I try use  'com.mikhaellopez:circularimageview:2.1.1'

But, something wrong, because in log:
Could not find method android.widget.ImageView.<init>, referenced from method  com.mikhaellopez.circularimageview.CircularImageView.<init>

Why could this be?

**Comment by lopspower** [comment]
Please try with the last version:
`compile 'com.mikhaellopez:circularimageview:3.0.0'`
