### ISSUE TITLE
I wasn't able to install this

### ISSUE THREAD

**Issue by RafaRuiz** [lopspower/CircularImageView#5]
If I import the library as project, I can't use the XML tags: "app:"... even adding the xmlns

and I can't preview it on layout:

"Missing styles. Is the correct theme chosen for this layout?
Use the Theme combo box above the layout to choose a different layout, or fix the theme style references.

Failed to find style 'circularImageViewStyle' in current theme"

**Comment by myanimal** [comment]
I think it's because a reference attribute is defined but never used. See here: https://github.com/lopspower/CircularImageView/blob/master/CircularImageView/res/values/attrs.xml#L12
