### ISSUE TITLE
The border color is getting filled inside the image

### ISSUE THREAD

**Issue by olx-gaurav-mishra** [lopspower/CircularImageView#51]
I am attaching image the border color is getting filled in the background as well. 
Any solution ? I am using color #005588
![img_profile_avatar](https://cloud.githubusercontent.com/assets/13196986/13109696/006b48e8-d5a1-11e5-86b6-f6fe9db60ef1.png)

![border](https://cloud.githubusercontent.com/assets/13196986/13109763/595da1b2-d5a1-11e5-9fcd-03018173711f.png)

**Comment by lopspower** [comment]
In this library, the border is actually a circle below the image.
You must either remove the border, or change the background image.

**Comment by olx-gaurav-mishra** [comment]
Thanks !
