### ISSUE TITLE
Error:(2) Attribute "civ_border_width" has already been defined

### ISSUE THREAD

**Issue by bliveinhack** [lopspower/CircularImageView#52]
The attributes you used is conflicts with 

> `play-services-wallet\8.4.0\res\values\wallet_colors.xml`

Affected attributes :
- "civ_border_width"
- "civ_border_color"

**Comment by lopspower** [comment]
Thanks for your feedback. Indeed, it's annoying.

**Comment by lopspower** [comment]
I tried with the latest version of `play-services-wallet` and I have no problems:

```groovy
implementation 'com.google.android.gms:play-services-wallet:16.0.1'
```

Do you still have the problem? I will close the ticket that can be reopened if the problem persists. Thank you, Mikhael.
