### ISSUE TITLE
Transparent part converted to black color on setting border = false.

### ISSUE THREAD

**Issue by hemantparmar23** [lopspower/CircularImageView#56]
Tried using a png image with transparent part.
when using app:civ_border="false" the transparent part was converted to black color.
it regained the transparency on setting  app:civ_border="true".

**Comment by sauraz** [comment]
Use this.
            app:civ_border="true"
            app:civ_border_width="0dp"

**Comment by vasskob** [comment]
Have the same problem. When used app:civ_border="false" background is black. When      app:civ_border="true" background is white & width="0dp" doesn't help at all. But I need a border with some width & transparent image. Any idea?

**Comment by tomospin** [comment]
I also found the black color problem
        app:civ_border_color="#FFFFFF"
        app:civ_border_width="4dp"
        app:civ_border="true"
        app:civ_shadow="true"
        app:civ_shadow_radius="0"
This setting can fix the problem. The main key is that civ_shadow must be true and radius must = 0

**Comment by lopspower** [comment]
You now used `civ_background_color` properties or `setBackgroundColor` method to set background color for png image.
