### ISSUE TITLE
Update manifest to allow overriding

### ISSUE THREAD

**Issue by jdulaney** [lopspower/CircularImageView#57]
Add in `tools:replace="android:allowBackup"` so that apps can provide their own settings. Otherwise, the manifest merger fails

> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:31:9-36
>     is also present at [com.mikhaellopez:circularimageview:3.0.2] AndroidManifest.xml:12:9-35 value=(true).
>     Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:29:5-141:19 to override.

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/74a62546086287f3d16c0f2a59a60f7e5d153bfd](https://github.com/lopspower/CircularImageView/commit/74a62546086287f3d16c0f2a59a60f7e5d153bfd)
