### ISSUE TITLE
height and width

### ISSUE THREAD

**Issue by sarang1996** [lopspower/CircularImageView#59]
I have to add hard corded values of height and width because of center inside scaltype. wrap_content doesn't work,any help? @lopspower

**Comment by chitgoks** [comment]
yes. even adding attribute android:scaleType="fitCenter" which is the ImageView's default scale type does not work as this seems to get overridden.

**Comment by sarang1996** [comment]
how can i add the wrap_content. if you know then please help me out with some code. @chitgoks

**Comment by chitgoks** [comment]
er sorry, i did not continue using this.

**Comment by sarang1996** [comment]
ah! you are using another one for circular image. right? @chitgoks
