### ISSUE TITLE
2 pixels height

### ISSUE THREAD

**Issue by BraisGabin** [lopspower/CircularImageView#63]
Is there any good reason for this line? https://github.com/lopspower/CircularImageView/blob/master/circularimageview/src/main/java/com/mikhaellopez/circularimageview/CircularImageView.java#L288

It's breaking my alignment.

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/01c669dfae09d08a046ed79356a9f8e5e5fdc96d](https://github.com/lopspower/CircularImageView/commit/01c669dfae09d08a046ed79356a9f8e5e5fdc96d)
