### ISSUE TITLE
set color filter doesnt work

### ISSUE THREAD

**Issue by omidjoon** [lopspower/CircularImageView#64]
hi 
setColorFilter(R.color.colorAccent, PorterDuff.Mode.SRC_ATOP);

doesnt work , do you have any solution ?

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/67c8ac0b3b297ddde02a8055cfd276eec6240454](https://github.com/lopspower/CircularImageView/commit/67c8ac0b3b297ddde02a8055cfd276eec6240454)
