### ISSUE TITLE
How to make background also circular?

### ISSUE THREAD

**Issue by Sdghasemi** [lopspower/CircularImageView#66]
First of all thanks for the great library. In my case I also need to make ImageView background circular (not with border or shadow, just simple circle) while setting its resource.
I'd appreciate if you walk me through some solution to achieve that.

**Comment by lopspower** [comment]
It's now available, you can use this property:
`app:civ_background_color` or this method `setBackgroundColor`

**Comment by rranjithkumar100** [comment]
app:civ_background_color not available in latest version (4.0.1)

**Comment by lopspower** [comment]
@rranjithkumar100 this property is replace by `app:civ_circle_color`
