### ISSUE TITLE
Inconsistent Licenses

### ISSUE THREAD

**Issue by rharter** [lopspower/CircularImageView#67]
The readme states that the project is available under the Apache v2 license, but the LICENSE file says an MIT license.  I'm using the library in my app, and would like to attribute it in my open source licenses page, but I'm not sure which library to use.

**Comment by lopspower** [comment]
Sorry about that, it's fix on [https://github.com/lopspower/CircularImageView/commit/9dac87a452ebed6df823234e66708ddc7a2b766b](https://github.com/lopspower/CircularImageView/commit/9dac87a452ebed6df823234e66708ddc7a2b766b)
