### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by thatsVishal** [lopspower/CircularImageView#68]
I'am using picasso to load image into circular view, if I set the placeholder or the default image then it shows the regular background but it show black background if I use another image

**Comment by raiarainne** [comment]
I have same issue too
![screenshot_2017-07-02-21-43-20](https://user-images.githubusercontent.com/22143915/27770340-8e544ac0-5f6f-11e7-83a0-f5f0a3032579.png)

**Comment by thatsVishal** [comment]
Seems like there is no one who is currently working on this project, I have come up with a library called fresco by facebook, it does not gives such error.

**Comment by Rainer-Lang** [comment]
@thatsVishal Why not Glide?

**Comment by thatsVishal** [comment]
I haven't tried Glide. And yes, fresco provides colored border, but i am not sure with the shadow.

**Comment by raiarainne** [comment]
I found the reason.
in my case, the shadow was be occurred when i add touch event on the image view.
So i solved the issue as following.

<de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="67dp"
            android:layout_height="67dp"
            android:id="@+id/imv_profileimage"           
            android:src="@drawable/photo"
            android:background="@drawable/my_selector"
           />

- @drawable/my_selector.xml

<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white" android:state_pressed="true"/>
    <item android:drawable="@android:color/white"/>
</selector>

 Picasso.with(this).load(Commons.g_user.get_photoUrl()).centerInside().placeholder(R.drawable.photo).noFade().fit().into(profileimage);

I hope this will helpful for you. :)

**Comment by thatsVishal** [comment]
Thanks, I will try that.. :)

**Comment by tomospin** [comment]
I also found the black color problem
        app:civ_border_color="#FFFFFF"
        app:civ_border_width="4dp"
        app:civ_border="true"
        app:civ_shadow="true"
        app:civ_shadow_radius="0"
This setting can fix the problem. The main key is that civ_shadow must be true and radius must = 0

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/f5b294cd07ee000182d67d4e892671770bf43711](https://github.com/lopspower/CircularImageView/commit/f5b294cd07ee000182d67d4e892671770bf43711)

You can now used `civ_background_color` properties or `setBackgroundColor` method to set a background color for PNG image
