### ISSUE TITLE
App is crashing if image scale type is changed

### ISSUE THREAD

**Issue by abhiataero** [lopspower/CircularImageView#69]
Hi,
if i try to set image scale type property either by xml or in java ,app is crashing...
can you please tell ,whats the problem?
in code you have specified the scale type but cant change?????
 java.lang.IllegalArgumentException: ScaleType FIT_XY not supported. ScaleType.CENTER_CROP is used by default. So you don't need to use ScaleType.

**Comment by vishnudbimcs** [comment]
same here

**Comment by lopspower** [comment]
You can see a visual guide for Android ImageView ScaleType there:
[https://robots.thoughtbot.com/android-imageview-scaletype-a-visual-guide](https://robots.thoughtbot.com/android-imageview-scaletype-a-visual-guide)

With FIT_XY the image the image is distorted when it is not square. To prevent this, the default ScaleType in this library in ScaleType.CENTER_CROP.
