### ISSUE TITLE
Setting Background Color

### ISSUE THREAD

**Issue by alzahm** [lopspower/CircularImageView#71]
I was using your library for a while and it's great but no i'm switching to another library because i usually need to set background color as well and your library doesn't provide that. 
I wanted to suggest you add background color properties as well.

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/f5b294cd07ee000182d67d4e892671770bf43711](https://github.com/lopspower/CircularImageView/commit/f5b294cd07ee000182d67d4e892671770bf43711)

You can now used `civ_background_color` properties or `setBackgroundColor` method to set a background color for PNG image
