### ISSUE TITLE
Library shouldn't include android:allowBackup="true"

### ISSUE THREAD

**Issue by JonathanMercandalli** [lopspower/CircularImageView#72]
I don't think this should be set in the library. Is there a reason it is there?

**Comment by kaloyanroussevdespark** [comment]
I agree. Removing the library because of this

**Comment by rakeshvihan** [comment]
Same here for me 👎

**Comment by lopspower** [comment]
It's now fixed :)

**Comment by Mercandj** [comment]
Nice thks 👍
