### ISSUE TITLE
app:srcCompat doesn't work

### ISSUE THREAD

**Issue by Ab-Appletic** [lopspower/CircularImageView#73]
To use vector drawables, you have to use `app:srcCompat`. But it doesn't work with your view.

**Comment by kaserdan** [comment]
Yup, CircularImageView should extend AppCompatImageView

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/6947db2a744d289a24248db6926ac417d933566a](https://github.com/lopspower/CircularImageView/commit/6947db2a744d289a24248db6926ac417d933566a)
