### ISSUE TITLE
Crash on using android:adjustViewBounds="true"

### ISSUE THREAD

**Issue by brajkishore** [lopspower/CircularImageView#74]
App is crashing on using android:adjustViewBounds="true" attributes with this new version library .

**Comment by burnix** [comment]
Have the same problem

**Comment by eugenio-caicedo** [comment]
@lopspower I get the same error.

**Comment by lopspower** [comment]
The ScaleType is always CENTER_CROP and you'll get an exception if you try to change it. Enabling adjustViewBounds is not supported as this requires an unsupported ScaleType.
