### ISSUE TITLE
android:scaleType="centerInside" causes crash

### ISSUE THREAD

**Issue by Zapnologica** [lopspower/CircularImageView#76]
I recently updated to version  `3.0.2`  and it caused my image view  with `android:scaleType="centerInside"`  and it causes and XML layout exception.

**Comment by vishnudbimcs** [comment]
same here

**Comment by ahsanmuzafar** [comment]
crash on adding android:scalteType= "fitcenter" also

**Comment by babulpatel1309** [comment]
scaleType is not working at all.

**Comment by lopspower** [comment]
Duplicate from [https://github.com/lopspower/CircularImageView/issues/69](https://github.com/lopspower/CircularImageView/issues/69)
