### ISSUE TITLE
Please remove application tag attributes

### ISSUE THREAD

**Issue by ymytkalyk-waverleysoftware** [lopspower/CircularImageView#79]
Don't pollute application tag with attributes, e.g.

```xml
<application
        android:allowBackup="true"
        android:supportsRtl="true" />
```

Should be replaced with

```xml
<application/>
```

Because that adds the tags to main manifest while merging the library and conflicts with supportsRtl=false", etc.

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/74a62546086287f3d16c0f2a59a60f7e5d153bfd](https://github.com/lopspower/CircularImageView/commit/74a62546086287f3d16c0f2a59a60f7e5d153bfd)
