### ISSUE TITLE
It's have some problem in Glide v4!

### ISSUE THREAD

**Issue by wl386123298** [lopspower/CircularImageView#84]
RT

**Comment by amarilindra** [comment]
What is the problem exactly?

**Comment by DenoGeek** [comment]
too much memory allocation

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/227d12eb399ab18a54b06fd63f94b68d6d0493eb](https://github.com/lopspower/CircularImageView/commit/227d12eb399ab18a54b06fd63f94b68d6d0493eb)
