### ISSUE TITLE
Crash: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by duetdroid2018** [lopspower/CircularImageView#87]
I met a crash what I am using this library. Here is the stacktrace:

AndroidRuntime: Caused by: java.lang.IllegalArgumentException: ScaleType FIT_CENTER not supported. ScaleType.CENTER_CROP is used by default. So you don't need to use ScaleType.
AndroidRuntime: 	at com.mikhaellopez.circularimageview.CircularImageView.setScaleType(CircularImageView.java:118)
AndroidRuntime: 	at android.widget.ImageView.setAdjustViewBounds(ImageView.java:304)
AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:165)
AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:145)
AndroidRuntime: 	at com.mikhaellopez.circularimageview.CircularImageView.<init>(CircularImageView.java:50)
AndroidRuntime: 	at com.mikhaellopez.circularimageview.CircularImageView.<init>(CircularImageView.java:46)

I checked your code, and I found that you throw a IllegalArgumentException in line 118, because you only support ScaleType.CENTER_CROP. An exception will be thrown if user set android:adjustViewBounds="true", and then a crash will be triggered, which will make your library annoying.

Therefore, I think it would be better if you can provide more information about the scaletype you can support, instead of throw an exception directly.

**Comment by lopspower** [comment]
Yes, it's an exception returned by the library when you try to set a scale type different from the default value `ScaleType.CENTER_CROP`.
