### ISSUE TITLE
app:srcCompat is not supported 

### ISSUE THREAD

**Issue by kim24** [lopspower/CircularImageView#89]
when I use vectordrawable it is obligatory to use : app:srcCompat 
but when I do that the library doesn't show image anymore.

**Comment by lopspower** [comment]
Fix in [https://github.com/lopspower/CircularImageView/commit/6947db2a744d289a24248db6926ac417d933566a](https://github.com/lopspower/CircularImageView/commit/6947db2a744d289a24248db6926ac417d933566a)
