### ISSUE TITLE
Relicense the project under MIT?

### ISSUE THREAD

**Issue by rschiang** [lopspower/CircularImageView#9]
Hi Lopez,

Stumbled upon your project and noticed it is using Creative Commons as project license. CC license is not created specifically for computer programs, and thus does not offer much protection. It would be better if you release your project in MIT or GPL, which eliminates you from those legal disputes.

Here's a [StackOverflow question](http://stackoverflow.com/questions/243196/what-is-the-difference-between-creative-commons-and-gpl-licensing) regarding CC license, and GitHub also offer a website to [help you choose a license.](http://choosealicense.com)

Hope this helps!

**Comment by lopspower** [comment]
Thank you for you help. Does the current license is good?

**Comment by rschiang** [comment]
MIT is cool enough! May the project live long and prosper :D

**Comment by Philio** [comment]
You might want to also consider the Apache license (it's probably the most popular option for Android projects), particularly as the Android source code uses the Apache license (hence, if you use anything from Android in your project you don't have to worry about managing multiple licenses).

**Comment by lopspower** [comment]
Thank Philio, I changed it to Apache Licence 2.0
