### ISSUE TITLE
The circular image with border shows border color in bacground for transparent png images

### ISSUE THREAD

**Issue by prathameshtal** [lopspower/CircularImageView#90]
The transparent png image shows background color in background.

**Comment by lopspower** [comment]
Fix on [https://github.com/lopspower/CircularImageView/commit/f5b294cd07ee000182d67d4e892671770bf43711](https://github.com/lopspower/CircularImageView/commit/f5b294cd07ee000182d67d4e892671770bf43711)

You can now used `civ_background_color` properties or `setBackgroundColor` method to set a background color for PNG image
