### ISSUE TITLE
Issues with Android oreo 8.0

### ISSUE THREAD

**Issue by MahmoudiOussama** [lopspower/CircularImageView#93]
I am using this library in my project, and i am facing app crashes only with devices running Android 8.0.
I am using Firebase Crashlitycs and this is a screenshot of the crash error : 

![image](https://user-images.githubusercontent.com/25067744/44155931-7f2c8692-a0a6-11e8-9737-865ba93a3fd2.png)

**Comment by MahmoudiOussama** [comment]
People are talking about this problem [in here](https://github.com/bumptech/glide/issues/2309).
The problem occurs when using Glide to download and display images while using the option **DecodeFormat.PREFER_ARGB_8888**.

Someone suggested to use latest Glide version and instead of **DecodeFormat.PREFER_ARGB_8888** use **DecodeFormat.PREFER_ARGB_8888_DISALLOW_HARDWARE**.

**Comment by lopspower** [comment]
I think it's an issue from Glide, not from this library:
[https://github.com/wasabeef/glide-transformations/issues/95](https://github.com/wasabeef/glide-transformations/issues/95)
