### ISSUE TITLE
CircularImageView suddenly not displayed on some layout

### ISSUE THREAD

**Issue by kareemzok** [lopspower/CircularImageView#94]
Hello , 

CircularImageView is not displayed on some of the activity having the same layout using adapter. How come it was working then it stopped? and in other activity the same CircularImageView  is working 
Any advice plz?

**Comment by kareemzok** [comment]
if no one has an answer or can help I will move to another library.

**Comment by NayanaRBhoj** [comment]
@kareemzok did you found any solution for this?

**Comment by kareemzok** [comment]
hello @NayanaRBhoj, yes I did find but I moved to Fresco library.
Solution was in   `android:hardwareAccelerated="false" `in manifest file. The value was truechanged it to false it worked perfectly

**Comment by nishkul** [comment]
I have solved is this  issue by adding this line after setting image using glide 
   mCircularIV.setDrawingCacheEnabled(true)
now is working fine
