### ISSUE TITLE
Image is getting cut off.

### ISSUE THREAD

**Issue by Tamir198** [lopspower/CircularImageView#95]
When I try to use the library on "galaxy j 7 pro - 2017"(api level 24) my image in getting cut off 
![round_image](https://user-images.githubusercontent.com/34707669/45028984-c3e0e180-b04f-11e8-80d4-799752d8256c.jpeg)

**Comment by kareemzok** [comment]
i m having same thing on most of activities and no one has replied to my issue

**Comment by Tamir198** [comment]
@kareemzok 
eventually, I handled it with glide library 
check this http://www.gadgetsaint.com/android/circular-images-glide-library-android/#.W6P912hvaUm
for any question feel free to connect me via mail - 1tamir198@gmial.com

**Comment by kareemzok** [comment]
I m using picasso but i thinkin to move to fresco since all feedback says that its much faster @tamir198
